apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: default
spec:
  chart:
    spec:
      chart: ./hello-world-chart
      sourceRef:
        kind: GitRepository
        name: hello-world-repo
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ecr_uri/rev-hello-world #to be updated
      tag: latest
